### ISSUE TITLE
[ ENHANCEMENT ] - List services on UP

### ISSUE THREAD

**Issue by BobbyBakes** [meqif/docker-compose-mode#26]
Looking to contribute but new to spacemacs and lisp. 

The idea: 
Parse docker-compose.yml to list services when spinning one up individually. 

Looking for guidance. 
bobby.a.baker@gmail.com

**Comment by meqif** [comment]
Hi @BobbyBakes, thanks for showing an interest in contributing!

Alas, I don't have any bandwidth available to do a proper job of mentoring you through the implementation of that change.

Additionally, the change you propose seems to go beyond the scope of this project, which is limited to improving the reading and editing experience for docker-compose files (e.g. providing better keyword completion or improved syntax highlighting). May I suggest doing so in a fork, or better yet, in a separate package?

Thanks again!

**Comment by BobbyBakes** [comment]
Sounds good! Thanks for the quick response !

**Comment by BobbyBakes** [comment]
Back to this. Apologies. 

The enhancement i had in mind, might already be in existence. 

scenario: U, U,  (docker compose up {service} will call docker-compose config --services. as if it is attempting to list the services available.  I then am prompted to enter the service. 

Was there intention of listing services to mnemonically input the service name? If so, this is what i am looking for, to avoid the typing in of the service every time.

**Comment by BobbyBakes** [comment]
Thanks for the feedback. This exists when the list of services is generated with {docker-compose config --services}. I didn't realize i could auto-complete when bringing up a service. All seems to be good in the world. Thank you again! Hoping to help contribute one day.
